use SUBTARGET
Signed-off-by: Paul Spooren <mail@aparcar.org>

diff --git a/meta b/meta
--- a/meta
+++ b/meta
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
 #
 # based on https://github.com/openwrt/packages/blob/master/.travis_do.sh
 
@@ -8,16 +8,16 @@ ROOT_DIR="$PWD"                 # where the script is
 DISTRO="${DISTRO:-openwrt}"     # the folder where to store created files
 RELEASE="${RELEASE:-17.01.5}"   # default release
 BASE_URL="${BASE_URL:-https://downloads.openwrt.org}" # download imagebuilders
-BASE_PATH="$DISTRO/$RELEASE/$TARGET"            # structure for storing stuff
+BASE_PATH="$DISTRO/$RELEASE/$TARGET/$SUBTARGET" # structure for storing stuff
 IB_DIR="$ROOT_DIR/imagebuilder/$BASE_PATH"      # where to store imagebuilders
 BIN_DIR="${BIN_DIR:-$ROOT_DIR/bin/$BASE_PATH}"  # where to store created images
 IB="imagebuilder"   # search sha256sums for this string to find imagebuilder
 
 
 [ "$RELEASE" != "snapshots" ] && [ -z "$SNAPSHOTS" ] && {
-    TARGETS_URL="$BASE_URL/releases/$RELEASE/targets/$TARGET"
+    TARGETS_URL="$BASE_URL/releases/$RELEASE/targets/$TARGET/$SUBTARGET"
 } || {
-    TARGETS_URL="$BASE_URL/snapshots/targets/$TARGET"
+    TARGETS_URL="$BASE_URL/snapshots/targets/$TARGET/$SUBTARGET"
     RELEASE="snapshots"
     SNAPSHOTS=1
 }
@@ -120,5 +120,6 @@ info() {
 
 # check if required vars a given
 [ -n "$TARGET" ] || die "missing $\$TARGET"
+[ -n "$SUBTARGET" ] || die "missing $\$SUBTARGET"
 
 $@
